[package]
name = "feather"
version = "1.0.0"
authors = ["Xaeroxe <kieseljake@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.10"
clap = "2.33"
ring = "0.16"
